# Generated by Django 6.0.5 on 2026-05-28 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textmessage', models.TextField(max_length=255, verbose_name='Текст сообщения')),
                ('datemesage', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки сообщения')),
                ('reactionscount', models.PositiveIntegerField(default=0, verbose_name='Количество реакций(Лайков)')),
                ('isprivate', models.BooleanField(default=False, verbose_name='Личное ли это сообщение?(Да|Нет)')),
                ('usermessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя, отправившего сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
            },
        ),
    ]
