# Generated by Django 6.0.5 on 2026-05-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_user_options_user_gender_user_is_banned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='datemesage',
            new_name='datemessage',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='isprivate',
            new_name='is_private',
        ),
    ]
